### ISSUE TITLE
use in theme

### ISSUE THREAD

**Issue by jojsonn** [Catapult-Themes/Whizzie#2]
Hello, I want to ask can I use Whizzie in my own theme for commercial use and make some changes in your code?

**Comment by plugin-republic** [comment]
Hi - yes, no problem. Please use it.

If you have any useful changes, it would be good to share them here. 

Also, I'd appreciate a link to the original article if possible: https://catapultthemes.com/whizzie-a-wordpress-theme-setup-wizard/.

Please let me know how you get on.

Gareth
