### ISSUE TITLE
Import Content and Customizer Options

### ISSUE THREAD

**Issue by troytempleman** [Catapult-Themes/Whizzie#3]
Hi Gareth,

Great plugin! I'm currently using Merlin for my theme but running into issues with the Theme Check plugin, so looking for something simpler and "wordpress-y" like this. 

Only thing missing for me is an option to import .xml WordPress content and .dat customizer settings. Any ideas how to do this?

Thanks!

**Comment by plugin-republic** [comment]
Hi Troy

Thanks for your comment. I'm not doing any development work on this project at the moment so unfortunately I don't have any solution for your question.

Thanks

Gareth
